### ISSUE TITLE
Breaks quick edit functionality

### ISSUE THREAD

**Issue by Rarst** [franz-josef-kaiser/current-admin-info#1]
Enabling plugin mangles quick edit functionality of post list screens in admin.

**Comment by franz-josef-kaiser** [comment]
Traced down to [`current_admin_globals :: markup()`](https://github.com/franz-josef-kaiser/current-admin-info/blob/master/inc/globals.class.php#L77). 

Removing the MarkUp fixes it. From a `var_dump()` of the MarkUp and a short run of manual beautification, there's nothing that seems to be wrong. All tags are opened/closed properly.

**Comment by franz-josef-kaiser** [comment]
Traced down to using the wrong quotes around the string for `sprintf()`.

**Comment by franz-josef-kaiser** [comment]
Done in this https://github.com/franz-josef-kaiser/current-admin-info/commit/139e930896f6dbd4ed2d9c30eadff2bfc07dc2f6 commit. Sadly it's now not as pretty anymore. WP uses `$( ".widefat" )` to trigger stuff all over different files. Sad, but what shall I do.
